name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: ghcr.io/thombashi/python-ci:3.12

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: make check
